export const animalFields = {
  NAME: 'name',
  BIRTH_DAY: 'birthDay',
  GENDER: 'gender',
  BREED: 'breed',
  SIZE: 'size',
  IMAGES: 'images',
  DESCRIPTION: 'description',
  TYPE: 'type',
  LIKES_COUNT: 'likesCount',
  DISLIKES_COUNT: 'dislikesCount',
  ACTIVE: 'active',
  USER_ID: 'userId',
  SHELTER_ID: 'shelterId',
  BRANCH_ID: 'branchId',
  HYPOALLERGENIC: 'hypoallergenic',
  NEUTERED: 'neutered',
  VACCINATED: 'vaccinated',
};
