export const userFields = {
  FIRST_NAME: 'first_name',
  LAST_NAME: 'last_name',
  EMAIL: 'email',
  PASSWORD: 'password',
  PICTURE: 'picture',
  COUNTRY: 'country',
  LOCATION: 'LOCATION',
  AGE: 'age',
  EMAIL_CONFIRMATION_CODE: 'emailConfirmationCode',
  ACTIVE: 'active',
  GOOGLE: 'google',
  FACEBOOK: 'facebook',
  COMPLETED_ON_BOARD_QUESTIONS: 'completedonBoardQuestions',
  ROLE: 'role',
  SHELTER_ID: 'shelterId',
};
